#!/bin/bash

S3_PREFIX="public.nikhil.io/quotes"
S3_PREFIX_ESCAPED=$(echo $S3_PREFIX | sed 's/\//\\\//g')

cd sources
python generate_quotes_from_annotated.py > ../quotes.json
cd ..

rm -rf tmp
mkdir -p tmp

sed "s/\/quotes/http:\/\/"$S3_PREFIX_ESCAPED"\/quotes/" quotes.html > tmp/index.html
sed "s/\/quotes/http:\/\/"$S3_PREFIX_ESCAPED"\/quotes/" quotes.js > tmp/quotes.js
sed "s/\/loading/http:\/\/"$S3_PREFIX_ESCAPED"\/loading/" quotes.css > tmp/quotes.css
cp quotes.json loading.svg tmp/

cd tmp
for FILE in *; do
    gzip -9 $FILE
    mv $FILE.gz $FILE
done

aws s3 sync . "s3://"$S3_PREFIX/ \
    --delete \
    --profile nikhil.io \
    --content-encoding gzip

cd ..
rm -rf tmp
